services:
  sagemaker:
    build:
      context: ./sagemaker_container
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    env_file:
      - ./backend/.env
    depends_on:
      - sagemaker
